### ISSUE TITLE
Directives et chemins de log incorrects dans TP 6

### ISSUE THREAD

**Issue by camHQ** [ahpnils/cours-server-linux#3]
cours-server-linux / tp / debian / tp6-apache-basique.md

Etape 4

> Repérer dans /etc/apache2/sites-enable/000-default.conf les directives ErrorLog et AccessLog, et retrouver les fichiers correspondant dans /var/log/apache2.

Remplacer : 
- sites-enable par sites-enabled
- AccessLog par CustomLog
---------------------
Ajouter 'apache2' aux chemins d'accès des fichiers de log :

>  quelles informations trouve-t'on dans /var/log/access.log ?
    quelles informations trouve-t'on dans /var/log/error.log ?

> Depuis un terminal, lancer la commande tail -f /var/log/error.log (...)

> Couper tail, puis lancer la commande tail -f /var/log/access.log (...)

**Comment by ahpnils** [comment]
Merci beaucoup de ta remontée de bug 😊 je corrige ça dès que possible

**Comment by ahpnils** [comment]
De ce que je lis le PR #5 corrige tout ! Merci @Zenigata :-)
