### ISSUE TITLE
Ajout d'une directive dans TP13

### ISSUE THREAD

**Issue by camHQ** [ahpnils/cours-server-linux#4]
Etape 2.
Après avoir assigné le pool server13 en modifiant le fichier `/etc/php/7.4/fpm/pool.d/server13.conf` : 

Avec la commande `usermod`, ajouter l'utilisateur `www-data` (utiliser par nginx) au groupe `server13` afin d'autoriser l'accès en lecture et écriture au fichier server13.sock.

**Comment by ahpnils** [comment]
@camHQ est-ce que le commit https://github.com/ahpnils/cours-server-linux/commit/2b6a5412bd4c502c58967a48589cef01af09daa5 te semble clarifier les choses ?

**Comment by ahpnils** [comment]
Pas de nouvelles, bonnes nouvelles.
