### ISSUE TITLE
adresse ip pour serveur Preseed

### ISSUE THREAD

**Issue by gerisse** [ahpnils/cours-server-linux#6]
Dans le TP4, il faut , sauf erreur , aller chercher le fichier server13.cfg  sous l'ip de la gateway http://192.168.122.1:8080 .
Je ne comprends pas comment installer un fichier sous la gateway. Celle ci n'est elle pas interne à virt-manager ?
Merci

**Comment by ahpnils** [comment]
Le principe est de démarrer un serveur web depuis l'hyperviseur (via la commande Python donnée plus tôt dans le TP), dans l'emplacement contenant le fichier preseed, et de faire accéder la VM à ce serveur web.

L'adresse IP 192.168.122.1 est celle de l'hyperviseur dans le réseau libvirt par défaut.

**Comment by gerisse** [comment]
ah, oui, merci. Toujours l'impression que la gateway n'est pas accessible facilement. Elle se confond avec l'hôte, finalement.

**Comment by ahpnils** [comment]
Pour être exact, c'est que l'hôte est la gateway.
